function [cf,gof,out]=createFit_autobias(r1,s1,w,z)
%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(R1,S1,W)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  1

% Data from data set "s1 vs. r1 with w":
%     X = r1:
%     Y = s1:
%     Weights = w:

% Auto-generated by MATLAB on 24-May-2011 14:58:47

% Set up figure to receive data sets and fits

% --- Plot data that was originally in data set "s1 vs. r1 with w"
r1 = r1(:);
s1 = s1(:);
w = w(:);

% --- Create fit "fit 1"
ex_ = false(length(r1),1);
% ex_ = ex_ | (s1 <= 0);
% ex_ = ex_ | (s1 <= 0)|(r1>70);
fo_ = fitoptions('method','NonlinearLeastSquares','Lower',[100  1],'Upper',[100000   100]);
ok_ = isfinite(r1) & isfinite(s1) & isfinite(w);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [1000 10];
set(fo_,'Startpoint',st_);
set(fo_,'Weight',w(ok_));
set(fo_,'Exclude',ex_(ok_));
%rfun=@(x,M,z,c) lensing_rfunc(x,M,z,c);
ft_ = fittype('lensing_rfunc_autobias(x,M,z,c)',...
    'dependent',{'y'},'independent',{'x'},'problem','z',...
    'coefficients',{'M', 'c'});

% Fit this model using new data
if sum(~ex_(ok_))<2
    % Too many points excluded.
    error( 'GenerateMFile:NotEnoughDataAfterExclusionRule',...
        'Not enough data left to fit ''%s'' after applying exclusion rule ''%s''.',...
        'fit 1', '0' );
else
    [cf,gof,out] = fit(r1(ok_),s1(ok_),ft_,fo_,'problem',z);
end
% Alternatively uncomment the following lines to use coefficients from the
% original fit. You can use this choice to plot the original fit against new
% data.
%    cv_ = { 219.33685005949919855, 10.53913676203119465};
%    cf_ = cfit(ft_,cv_{:});

% Plot this fit
%h_ = plot(cf,'fit',0.95);
