HybMass=@(sigma,L) 10.^11.51*sigma.*(L/1e12).^0.74;
HybMassZ=@(sigma,L,z) 10.^11.15*sigma.^1.3.*(L/1e12).^0.78./(1+z).^5.8;
HybMassV=@(sigma,L,V) 10.^15.00*sigma.^0.98.*(L/1e12).^1.70./V.^0.99;
DynStep=@(sigma,N) 10.^8.83*min(N/12.0,1).^1.83.*sigma.^2;
DynVol=@(sigma,V) 10.^8.49*V.^0.6.*sigma.^1.28;
LumNew=@(L) 10.^14.23*(L/1e12).^1.076;
LumVol=@(L,V) 10.^17.46*(L/1e12).^1.99./V.^0.92;
pfull=[13.472071 -0.484484 -6.109942 1.143656 -0.448352 1.381457 0.405702];
grpmock.IterCenSM=grpmock.MstarIter;
FullMass=@(grp,p) 10.^p(1).*grp.VolMult.^p(2).*(1+grp.Zfof).^p(3).*grp.VelDisp.^p(4).*grp.Rad50.^p(5).*(grp.Luminosity/1e12).^p(6).*(grp.IterCenSM/1e12).^p(7);
psuper=[14.59,-1.963,14.96,1.114,-0.4615,1.208,0.4202,1.635];
SuperMass=@(grp) FullMass(grp,psuper).*grp.Mult.^psuper(8);
%% apply systematic corrections
HybMassZ=@(sigma,L,z) 10.^(11.15-0.14)*sigma.^(1.31+0.03).*(L/1e12).^(0.78+0.02).*(1+z).^(-5.79+0.18);
DynVol=@(sigma,V) 10.^(8.49-0.13)*V.^(0.61+0.02).*sigma.^1.28;
LumNew=@(L) 10.^(14.23-0.07)*(L/1e12).^(1.08+0.01);
LumVol=@(L,V) 10.^(17.46-0.40)*(L/1e12).^(1.99-0.10).*V.^(-0.92+0.10);
%%
grpmock.HybMass=HybMass(grpmock.VelDisp,grpmock.Luminosity);
grpmock.HybMassZ=HybMassZ(grpmock.VelDisp,grpmock.Luminosity,grpmock.Zfof);
grpmock.HybMassV=HybMassV(grpmock.VelDisp,grpmock.Luminosity,grpmock.VolMult);
grpmock.DynStep=DynStep(grpmock.VelDisp,grpmock.Mult);
grpmock.LumNew=LumNew(grpmock.Luminosity);
grpmock.DynVol=DynVol(grpmock.VelDisp,grpmock.VolMult);
grpmock.LumVol=LumVol(grpmock.Luminosity,grpmock.VolMult);
grpmock.FullMass=FullMass(grpmock,pfull);
grpmock.SuperMass=SuperMass(grpmock);
%%
figure;
f=grpmock.Mult>2;
loglog(grpmock.MIter(f),grpmock.HybMass(f),'b.','markersize',1);
hold on;
loglog(grpmock.MIter(f),grpmock.HybMassZ(f),'r.','markersize',1);
loglog(grpmock.MIter(f),grpmock.DynStep(f),'g.','markersize',1);
loglog(grpmock.MIter(f),grpmock.LumNew(f),'k.','markersize',1);
loglog(grpmock.MIter(f),grpmock.LumMass(f),'c.','markersize',1);
loglog(grpmock.MIter(f),grpmock.DynMass(f),'m.','markersize',1);
ylim([1e10,1e16]);
xlim([1e10,1e16]);
hold on;
plot([1e10,1e16],[1e10,1e16],'k-');
%%
smth=@(n) conv2(n,[0.05,0.1,0.05;0.1,0.4,0.1;0.05,0.1,0.05;],'same');
% smth=@(n) conv2(n,[0.02,0.05,0.02;0.05,0.72,0.05;0.02,0.05,0.02;],'same');
nbin=55;
percents=[0.1,0.3,0.6,0.9];
% levels=0.5:0.5:2;
figure;
f=grpmock.Mult>2;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.DynMass(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'r');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.LumMass(f)),[nbin,nbin],[10,16],[10,16]);
% [~,h2]=contour(xx,yy,log10((n+1)),levels,'g');hold on;
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.DynStep(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'b');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.LumNew(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'c');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.HybMass(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'m');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.MIter(f)),log10(grpmock.HybMassZ(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;
ylim([10,16]);
xlim([10,16]);
hold on;
plot([10,16],[10,16],'k-');
%%
% smth=@(n) n;
smth=@(n) conv2(n,[0.05,0.1,0.05;0.1,0.4,0.1;0.05,0.1,0.05;],'same');
% smth=@(n) conv2(n,[0.02,0.05,0.02;0.05,0.72,0.05;0.02,0.05,0.02;],'same');
nbin=55;
percents=[0.3,0.6,0.9];
% levels=0.5:0.5:2;
figure;
f=grpmock.Mult>2;
[xx,yy,n,s]=densitygrid(log10(grpmock.DynMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'r');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.LumMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.DynStep(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'b');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.LumNew(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'c');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.HybMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'m');hold on;
[xx,yy,n,s]=densitygrid(log10(grpmock.HybMassZ(f)),log10(grpmock.MIter(f)),[nbin,nbin],[10,16],[10,16]);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;
ylim([10,16]);
xlim([10,16]);
hold on;
plot([10,16],[10,16],'k-');
%%
mlim=[10,15];
smth=@(n) conv2(n,[0.05,0.1,0.05;0.1,0.4,0.1;0.05,0.1,0.05;],'same');
nbin=40;
percents=[0.3,0.6,0.8];
% levels=0.5:0.5:2;
figure;
x=log10(grpmock.FullMass);y=log10(grpmock.MIter);
f=grpmock.Mult>2&grpmock.Mult<5;
plot(x(f),y(f),'y.');hold on;
[xx,yy,n,s]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'r');hold on;
f=grpmock.Mult>=5&grpmock.Mult<10;
[xx,yy,n,s]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;
f=grpmock.Mult>=10
[xx,yy,n,s]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'b');hold on;
ylim(mlim);
xlim(mlim);
hold on;
plot(mlim,mlim,'k-');
%%
MultCut=5;
mlim=[11.,15];
cmap='cool';
smth=@(n) conv2(n,[0.05,0.1,0.05;0.1,0.4,0.1;0.05,0.1,0.05;],'same');
nbin=50;
percents=[0.3,0.6,0.9];
xbin=linspace(11,15,15);
myfigure;
ax=zeros(3,2);
f=grpmock.Mult>2;
ax(1,1)=subplot(3,2,1);
[xx,yy,n,s]=densitygrid(log10(grpmock.DynMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.DynMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.DynMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g--');
ff=grpmock.Mult>2&grpmock.Mult<MultCut;
[xmed,ymed,yl]=skeleton(log10(grpmock.DynMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(log10(grpmock.DynMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.5,'DynMass','fontsize',15);
%-----------------------------
ax(1,2)=subplot(3,2,2);
[xx,yy,n,s]=densitygrid(log10(grpmock.LumMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.LumMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.LumMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g--');
ff=grpmock.Mult<MultCut&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.LumMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(log10(grpmock.LumMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.5,'LumMass','fontsize',15);
%----------------------------
ax(2,1)=subplot(3,2,3);
x=log10(grpmock.DynStep);
% x=log10(grpmock.DynVol);
[xx,yy,n,s]=densitygrid(x(f),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g--');
ff=grpmock.Mult<MultCut&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
ylabel('$\log(M_h[\rm{M}_\odot/h])$');
text(11.2,14.5,'NewDynMass','fontsize',15);
% text(11.2,14.5,'DynVol','fontsize',15);
%----------------------------
ax(2,2)=subplot(3,2,4);
x=log10(grpmock.LumNew);
% x=log10(grpmock.LumVol);
[xx,yy,n,s]=densitygrid(x(f),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
h1=plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
h2=plot(xmed,ymed,'g--');
ff=grpmock.Mult<MultCut&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
h3=plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(x(ff),log10(grpmock.MIter(ff)),xbin);
h4=plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k-','linewidth',2);
l=legend([h1,h2,h3,h4],'$z<0.2$','$z>0.2$',['$N<',num2str(MultCut),'$'],['$N\ge',num2str(MultCut),'$']);
set(l,'location','southeast','interpreter','latex','box','off','fontsize',15);
text(11.2,14.5,'NewLumMass','fontsize',15);
% text(11.2,14.5,'LumVol','fontsize',15);
%----------------------------
ax(3,1)=subplot(3,2,5);
[xx,yy,n,s]=densitygrid(log10(grpmock.HybMass(f)),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g--');
ff=grpmock.Mult<MultCut&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMass(ff)),log10(grpmock.MIter(ff)),xbin);
plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.5,'HybMass','fontsize',15);
%---------------------------
ax(3,2)=subplot(3,2,6);
[xx,yy,n,s]=densitygrid(log10(grpmock.HybMassZ(f)),log10(grpmock.MIter(f)),[nbin,nbin],mlim,mlim);
[~,h2]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'k');hold on;colormap(cmap);
ff=grpmock.Zfof<0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMassZ(ff)),log10(grpmock.MIter(ff)),xbin);
h1=plot(xmed,ymed,'r--');
ff=grpmock.Zfof>0.2&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMassZ(ff)),log10(grpmock.MIter(ff)),xbin);
h2=plot(xmed,ymed,'g--');
ff=grpmock.Mult<MultCut&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMassZ(ff)),log10(grpmock.MIter(ff)),xbin);
h3=plot(xmed,ymed,'r-');
ff=grpmock.Mult>=MultCut;
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMassZ(ff)),log10(grpmock.MIter(ff)),xbin);
h4=plot(xmed,ymed,'g-');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(10,10.,'$\log(M_{est}[\rm{M}_\odot/h])$','fontsize',20);
text(11.2,14.5,'HybMassZ','fontsize',15);
%---------------------------
TightenSubplots(ax);
set(ax(1:2,:),'ytick',12:16);
set(ax(3,:),'ytick',11:16);
set(ax(:,2),'xtick',12:16);
set(ax(:,1),'xtick',11:16);
set(gcf,'papertype','A4');
set(gcf,'paperunits','centimeters','paperposition',[0.6,6,20,23]);
% print('-depsc','/work/Projects/Lensing/outputv4/paper/v3up8/Estimators2.eps');
%%
mlim=[11,15];
cmap='winter';
smth=@(n) conv2(n,[0.05,0.1,0.05;0.1,0.4,0.1;0.05,0.1,0.05;],'same');
smth=@(n) conv2(n,[0.08,0.15,0.08;0.15,0.23,0.15;0.08,0.15,0.08;],'same');
nbin=40;
percents=[0.3,0.6,0.9];
xbin=linspace(11,15,9);
myfigure;
y=log10(grpmock.MIter);
ax=zeros(3,2);
f=grpmock.Mult>2;
ax(1,1)=subplot(3,2,1);
x=log10(grpmock.DynMass);
[xx,yy,n]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.3,{'G3Cv1'; 'dynamical mass'},'fontsize',15);
%-----------------------------
ax(1,2)=subplot(3,2,2);
x=log10(grpmock.LumMass);
[xx,yy,n]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.3,{'G3Cv1'; 'luminosity mass'},'fontsize',15);
%----------------------------
ax(2,1)=subplot(3,2,3);
% x=log10(grpmock.DynStep);
x=log10(grpmock.DynVol);
[xx,yy,n]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
ylabel('$\log($True Halo Mass$[\rm{M}_\odot/h])$');
% text(11.2,14.5,'NewDynMass','fontsize',15);
text(11.2,14.5,'MLWL: $A\sigma_v^\alpha V_N^\beta$','fontsize',15);
%----------------------------
ax(2,2)=subplot(3,2,4);
x=log10(grpmock.LumNew);
% x=log10(grpmock.LumVol);
[xx,yy,n]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:','linewidth',2);
% l=legend([h1,h2,h3,h4],'$z<0.2$','$z>0.2$',['$N<',num2str(MultCut),'$'],['$N\ge',num2str(MultCut),'$']);
% set(l,'location','southeast','interpreter','latex','box','off','fontsize',15);
text(11.2,14.5,'MLWL: $AL^\alpha$','fontsize',15);
% text(11.2,14.5,'LumVol','fontsize',15);
%----------------------------
ax(3,1)=subplot(3,2,5);
x=log10(grpmock.HybMassZ);
[xx,yy,n,s]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(11.2,14.5,'MLWL: $A\sigma_v^\alpha L^\beta (1+z)^\gamma$','fontsize',15);
%---------------------------
ax(3,2)=subplot(3,2,6);
x=log10(grpmock.LumVol);
[xx,yy,n,s]=densitygrid(x(f),y(f),[nbin,nbin],mlim,mlim);
[~,h0]=contour(xx,yy,smth(n),percentile_to_density(n,percents),'g');hold on;colormap(cmap);
[xmed,ymed,yl]=skeleton(x(f),y(f),xbin);
plot(xmed,ymed,'r-');
plot(xmed,yl,'r--');
ylim(mlim);xlim(mlim);plot(mlim,mlim,'k:');
text(8,10.,'$\log($Estimated Halo Mass$[\rm{M}_\odot/h])$','fontsize',20);
text(11.2,14.5,'MLWL: $AL^\alpha V_N^\beta$','fontsize',15);
%---------------------------
TightenSubplots(ax);
set(ax(1:2,:),'ytick',12:16);
set(ax(3,:),'ytick',11:16);
set(ax(:,2),'xtick',12:16);
set(ax(:,1),'xtick',11:16);
set(gcf,'papertype','A4');
set(gcf,'paperunits','centimeters','paperposition',[0.6,6,20,23]);
print('-depsc','/work/Projects/Lensing/outputv4/paper/v3up8/extra/Estimators-poster.eps');
%%

figure;
f=grpmock.Zfof<0.5&grpmock.Mult>2;
[xmed,ymed,yl]=skeleton(log10(grpmock.DynMass(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'r-');hold on;
% plot(xmed,yl,'r--');
[xmed,ymed,yl]=skeleton(log10(grpmock.LumMass(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'g-');hold on;
% plot(xmed,yl,'g--');
[xmed,ymed,yl]=skeleton(log10(grpmock.DynStep(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'b-');hold on;
% plot(xmed,yl,'b--');
[xmed,ymed,yl]=skeleton(log10(grpmock.LumNew(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'c-');hold on;
% plot(xmed,yl,'c--');
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMass(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'m-');hold on;
% plot(xmed,yl,'m--');
[xmed,ymed,yl]=skeleton(log10(grpmock.HybMassZ(f)),log10(grpmock.MIter(f)),xbin);
plot(xmed,ymed,'k-');hold on;
% plot(xmed,yl,'k--');
ylim(mlim);
xlim(mlim);
hold on;
plot(mlim,mlim,'k-');
%%
grp.DynStep=DynStep(grp.VelDisp,grp.Mult);
grp.DynVol=DynVol(grp.VelDisp,grp.VolMult);
grp.LumNew=LumNew(grp.Luminosity);
grp.LumVol=LumVol(grp.Luminosity,grp.VolMult);
grp.HybMass=HybMass(grp.VelDisp,grp.Luminosity);
grp.HybMassZ=HybMassZ(grp.VelDisp,grp.Luminosity,grp.Zfof);
grp.FullMass=FullMass(grp,pfull);
%%
compare_masscontour(grp,'DynStep','DynVol')
