file='/mnt/charon/Lensing/output/shearprof_H1.Angular.txt';
h1=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_H2.Angular.txt';
h2=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_H3.Angular.txt';
h3=importdata(file,'\t',1);
figure;
errorbar(h1.data(:,5)*180/pi,h1.data(:,2),h1.data(:,4),'r.');
hold on;
errorbar(h2.data(:,5)*180/pi,h2.data(:,2),h2.data(:,4),'go');
errorbar(h3.data(:,5)*180/pi,h3.data(:,2),h3.data(:,4),'bs');
set(gca,'xscale','log');
xlabel('\theta (degrees)');ylabel('e_{t}');
print('-depsc','wlShear_angular.eps');
%%
file='/mnt/charon/Lensing/output/shearprof_D1.txt';
d1=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_D2.txt';
d2=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_D3.txt';
d3=importdata(file,'\t',1);
errorbar(d1.data(:,4),d1.data(:,1),d1.data(:,3),'g.');
hold on;
errorbar(d2.data(:,4),d2.data(:,1),d2.data(:,3),'go');
errorbar(d3.data(:,4),d3.data(:,1),d3.data(:,3),'gs');
file='/mnt/charon/Lensing/output/shearprof_L1.txt';
l1=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_L2.txt';
l2=importdata(file,'\t',1);
file='/mnt/charon/Lensing/output/shearprof_L3.txt';
l3=importdata(file,'\t',1);
errorbar(l1.data(:,4),l1.data(:,1),l1.data(:,3),'b.');
hold on;
errorbar(l2.data(:,4),l2.data(:,1),l2.data(:,3),'bo');
errorbar(l3.data(:,4),l3.data(:,1),l3.data(:,3),'bs');
set(gca,'xscale','log');
set(gca,'yscale','log');
